## This file generated by InlineX::C2XS (version 0.15) using Inline::C (version 0.46)
package Text::MatchRatingCodex;
use strict;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Text::MatchRatingCodex::VERSION = '0.01';

DynaLoader::bootstrap Text::MatchRatingCodex $Text::MatchRatingCodex::VERSION;

@Text::MatchRatingCodex::EXPORT = ();
@Text::MatchRatingCodex::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;

=pod

=head1 NAME

Text::MatchRatingCodex - MatchRatingCodex algorithm

=head1 SYNOPSIS

      use Text::MatchRatingCodex;
      $encoded_string = Text::MatchRatingCodex::match_rating_codex($string);

=head1 DESCRIPTION

The MatchRatingCodex search algorithm is a phonetic algorithm.

=head1 AUTHOR

    Stefan Gipper <stefanos@cpan.org>, http://www.coder-world.de/

=head1 COPYRIGHT

Text::MatchRatingCodex is Copyright (c) 2010 Stefan Gipper
All rights reserved.

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

=head1 SEE ALSO



=cut
